name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  actions: write
  checks: read
  contents: write
  deployments: write
  issues: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'
      - name: Clean
        run: ./gradlew clean
      - name: Build and test
        run: ./gradlew build test --parallel
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
      - name: Log test coverage percentage
        run: |
          echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "Branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update test coverage badge'
          add: '*.svg'
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
